buffer.h
SSH_BUFFER_PACK_END
ssh_buffer_pack
ssh_buffer_unpack
LIBSSH_API void ssh_buffer_free(ssh_buffer buffer)
LIBSSH_API void* ssh_buffer_get_begin(ssh_buffer buffer)
LIBSSH_API uint32_t ssh_buffer_get_len(ssh_buffer buffer)
LIBSSH_API ssh_buffer ssh_buffer_new(void)
Create a new SSH buffer.
A newly initialized SSH buffer, NULL on error.
Referenced by ssh_channel_new, ssh_channel_open_forward, ssh_channel_request_pty_size, ssh_channel_change_pty_size, ssh_channel_request_subsystem, ssh_channel_request_x11, ssh_channel_listen_forward, ssh_channel_cancel_forward, ssh_channel_request_env, ssh_channel_request_exec, ssh_channel_request_send_signal, ssh_channel_open_reverse_forward, ssh_channel_open_x11, ssh_channel_request_send_exit_status, ssh_channel_request_send_exit_signal, ssh_pcap_file_write_packet, ssh_pcap_file_open, ssh_pki_import_pubkey_blob, ssh_pki_openssh_privkey_export, ssh_new, sftp_get_error, sftp_init, sftp_opendir, sftp_readdir, sftp_attributes_free, sftp_open, sftp_read, sftp_async_read_begin, sftp_write, sftp_unlink, sftp_rmdir, sftp_mkdir, sftp_rename, sftp_setstat, sftp_symlink, sftp_readlink, sftp_statvfs, sftp_fstatvfs, sftp_canonicalize_path, sftp_fstat, ssh_socket_new.
void ssh_buffer_set_secure(ssh_buffer buffer)
Sets the buffer as secure.
A secure buffer will never leave cleartext data in the heap after being reallocated or freed. buffer buffer to set secure.
int buffer_add_ssh_string(ssh_buffer buffer, ssh_string string)
int buffer_add_u8(ssh_buffer buffer, uint8_t data)
int buffer_add_u16(ssh_buffer buffer, uint16_t data)
int buffer_add_u32(ssh_buffer buffer, uint32_t data)
int buffer_add_u64(ssh_buffer buffer, uint64_t data)
int ssh_buffer_add_data(ssh_buffer buffer, const void *data, uint32_t len)
int ssh_buffer_validate_length(struct ssh_buffer_struct *buffer, size_t len)
Valdiates that the given length can be obtained from the buffer.
buffer The buffer to read from. len The length to be checked. SSH_OK if the length is valid, SSH_ERROR otherwise.
Referenced by buffer_get_data, buffer_get_ssh_string, ssh_buffer_unpack_va.
int ssh_buffer_pack_va(struct ssh_buffer_struct *buffer, const char *format, int argc, va_list ap)
Add multiple values in a buffer on a single function call.
buffer The buffer to add to format A format string of arguments. ap A va_list of arguments. SSH_OK on success SSH_ERROR on error ssh_buffer_add_format() for format list values.
References buffer_add_u8, buffer_add_u16, buffer_add_u32, buffer_add_u64, buffer_add_ssh_string, ssh_buffer_add_data.
Referenced by _ssh_buffer_pack.
int _ssh_buffer_pack(struct ssh_buffer_struct *buffer, const char *format, int argc,...)
Add multiple values in a buffer on a single function call.
buffer The buffer to add to format A format string of arguments. This string contains single letters describing the order and type of arguments: 'b': uint8_t (pushed in network byte order) 'w': uint16_t (pushed in network byte order) 'd': uint32_t (pushed in network byte order) 'q': uint64_t (pushed in network byte order) 'S': ssh_string 's': char * (C string, pushed as SSH string) 't': char * (C string, pushed as free text) 'P': size_t, void * (len of data, pointer to data) only pushes data. 'B': bignum (pushed as SSH string) SSH_OK on success SSH_ERROR on error when using 'P' with a constant size (e.g. 8), do not forget to cast to (size_t).
References ssh_buffer_pack_va.
int ssh_buffer_unpack_va(struct ssh_buffer_struct *buffer, const char *format, int argc, va_list ap)
Get multiple values from a buffer on a single function call.
buffer The buffer to get from format A format string of arguments. ap A va_list of arguments. SSH_OK on success SSH_ERROR on error ssh_buffer_get_format() for format list values.
References ssh_buffer_get_len, buffer_get_u8, buffer_get_data, buffer_get_u32, buffer_get_u64, buffer_get_ssh_string, ssh_buffer_validate_length.
Referenced by _ssh_buffer_unpack.
int _ssh_buffer_unpack(struct ssh_buffer_struct *buffer, const char *format, int argc,...)
Get multiple values from a buffer on a single function call.
buffer The buffer to get from format A format string of arguments. This string contains single letters describing the order and type of arguments: 'b': uint8_t * (pulled in network byte order) 'w': uint16_t * (pulled in network byte order) 'd': uint32_t * (pulled in network byte order) 'q': uint64_t * (pulled in network byte order) 'S': ssh_string * 's': char ** (C string, pulled as SSH string) 'P': size_t, void ** (len of data, pointer to data) only pulls data. SSH_OK on success SSH_ERROR on error when using 'P' with a constant size (e.g. 8), do not forget to cast to (size_t).
References ssh_buffer_unpack_va.
int buffer_prepend_data(ssh_buffer buffer, const void *data, uint32_t len)
int buffer_add_buffer(ssh_buffer buffer, ssh_buffer source)
int ssh_buffer_reinit(ssh_buffer buffer)
void* buffer_get_rest(ssh_buffer buffer)
uint32_t buffer_get_rest_len(ssh_buffer buffer)
int buffer_get_u8(ssh_buffer buffer, uint8_t *data)
int buffer_get_u32(ssh_buffer buffer, uint32_t *data)
int buffer_get_u64(ssh_buffer buffer, uint64_t *data)
uint32_t buffer_get_data(ssh_buffer buffer, void *data, uint32_t requestedlen)
ssh_string buffer_get_ssh_string(ssh_buffer buffer)
ssh_string buffer_get_mpint(ssh_buffer buffer)
uint32_t buffer_pass_bytes_end(ssh_buffer buffer, uint32_t len)
uint32_t buffer_pass_bytes(ssh_buffer buffer, uint32_t len)