buffer.c
buffer_verify
struct ssh_buffer_struct* ssh_buffer_new(void)
Create a new SSH buffer.
A newly initialized SSH buffer, NULL on error.
Referenced by sftp_async_read_begin, sftp_attributes_free, sftp_canonicalize_path, sftp_fstat, sftp_fstatvfs, sftp_get_error, sftp_init, sftp_mkdir, sftp_open, sftp_opendir, sftp_read, sftp_readdir, sftp_readlink, sftp_rename, sftp_rmdir, sftp_setstat, sftp_statvfs, sftp_symlink, sftp_unlink, sftp_write, ssh_channel_cancel_forward, ssh_channel_change_pty_size, ssh_channel_listen_forward, ssh_channel_new, ssh_channel_open_forward, ssh_channel_open_reverse_forward, ssh_channel_open_x11, ssh_channel_request_env, ssh_channel_request_exec, ssh_channel_request_pty_size, ssh_channel_request_send_exit_signal, ssh_channel_request_send_exit_status, ssh_channel_request_send_signal, ssh_channel_request_subsystem, ssh_channel_request_x11, ssh_new, ssh_pcap_file_open, ssh_pcap_file_write_packet, ssh_pki_import_pubkey_blob, ssh_pki_openssh_privkey_export, ssh_socket_new.
void ssh_buffer_free(struct ssh_buffer_struct *buffer)
Deallocate a SSH buffer.
buffer The buffer to free.
Referenced by sftp_async_read_begin, sftp_attributes_free, sftp_canonicalize_path, sftp_closedir, sftp_fstat, sftp_fstatvfs, sftp_get_error, sftp_mkdir, sftp_open, sftp_opendir, sftp_read, sftp_readdir, sftp_readlink, sftp_rename, sftp_rmdir, sftp_setstat, sftp_statvfs, sftp_symlink, sftp_unlink, sftp_write, ssh_channel_new, ssh_gssapi_get_creds, ssh_pki_import_pubkey_base64, ssh_socket_free, ssh_socket_new.
void ssh_buffer_set_secure(ssh_buffer buffer)
Sets the buffer as secure.
A secure buffer will never leave cleartext data in the heap after being reallocated or freed. buffer buffer to set secure.
static int realloc_buffer(struct ssh_buffer_struct *buffer, size_t needed)
static void buffer_shift(ssh_buffer buffer)
shifts a buffer to remove unused data in the beginning
buffer SSH buffer
int ssh_buffer_reinit(struct ssh_buffer_struct *buffer)
Reinitialize a SSH buffer.
buffer The buffer to reinitialize. 0 on success, < 0 on error.
Referenced by channel_read_buffer, ssh_channel_close, ssh_channel_send_eof, ssh_gssapi_get_creds, ssh_send_debug, ssh_send_ignore, ssh_socket_reset.
int ssh_buffer_add_data(struct ssh_buffer_struct *buffer, const void *data, uint32_t len)
Add data at the tail of a buffer.
buffer The buffer to add the data. data A pointer to the data to add. len The length of the data to add. 0 on success, < 0 on error.
Referenced by buffer_add_buffer, buffer_add_ssh_string, buffer_add_u16, buffer_add_u32, buffer_add_u64, buffer_add_u8, channel_read_buffer, ssh_buffer_pack_va, ssh_pki_import_pubkey_blob, ssh_socket_write.
int buffer_add_ssh_string(struct ssh_buffer_struct *buffer, struct ssh_string_struct *string)
Add a SSH string to the tail of a buffer.
buffer The buffer to add the string. string The SSH String to add. 0 on success, < 0 on error.
References ssh_buffer_add_data, ssh_string_len.
Referenced by sftp_attributes_free, sftp_canonicalize_path, sftp_fstat, sftp_fstatvfs, sftp_opendir, sftp_readdir, sftp_readlink, sftp_setstat, sftp_statvfs, ssh_buffer_pack_va, ssh_gssapi_get_creds.
int buffer_add_u32(struct ssh_buffer_struct *buffer, uint32_t data)
Add a 32 bits unsigned integer to the tail of a buffer.
buffer The buffer to add the integer. data The 32 bits integer to add. 0 on success, -1 on error.
References ssh_buffer_add_data.
Referenced by sftp_attributes_free, sftp_canonicalize_path, sftp_fstat, sftp_fstatvfs, sftp_opendir, sftp_readdir, sftp_readlink, sftp_rename, sftp_setstat, sftp_statvfs, ssh_buffer_pack_va, ssh_pcap_file_open, ssh_pcap_file_write_packet.
int buffer_add_u16(struct ssh_buffer_struct *buffer, uint16_t data)
Add a 16 bits unsigned integer to the tail of a buffer.
buffer The buffer to add the integer. data The 16 bits integer to add. 0 on success, -1 on error.
References ssh_buffer_add_data.
Referenced by ssh_buffer_pack_va.
int buffer_add_u64(struct ssh_buffer_struct *buffer, uint64_t data)
Add a 64 bits unsigned integer to the tail of a buffer.
buffer The buffer to add the integer. data The 64 bits integer to add. 0 on success, -1 on error.
References ssh_buffer_add_data.
Referenced by ssh_buffer_pack_va.
int buffer_add_u8(struct ssh_buffer_struct *buffer, uint8_t data)
Add a 8 bits unsigned integer to the tail of a buffer.
buffer The buffer to add the integer. data The 8 bits integer to add. 0 on success, -1 on error.
References ssh_buffer_add_data.
Referenced by ssh_buffer_pack_va.
int buffer_prepend_data(struct ssh_buffer_struct *buffer, const void *data, uint32_t len)
Add data at the head of a buffer.
buffer The buffer to add the data. data The data to prepend. len The length of data to prepend. 0 on success, -1 on error.
int buffer_add_buffer(struct ssh_buffer_struct *buffer, struct ssh_buffer_struct *source)
Append data from a buffer to the tail of another buffer.
buffer The destination buffer. source The source buffer to append. It doesn't take the position of the buffer into account. 0 on success, -1 on error.
References buffer_get_rest, buffer_get_rest_len, ssh_buffer_add_data.
Referenced by ssh_pcap_file_write_packet.
void* ssh_buffer_get_begin(struct ssh_buffer_struct *buffer)
Get a pointer on the head of a buffer.
buffer The buffer to get the head pointer. A data pointer on the head. It doesn't take the position into account. Don't expect data to be nul-terminated. buffer_get_rest() buffer_get_len()
Referenced by ssh_gssapi_get_creds.
void* buffer_get_rest(struct ssh_buffer_struct *buffer)
Get a pointer to the head of a buffer at the current position.
buffer The buffer to get the head pointer. A pointer to the data from current position. buffer_get_rest_len() buffer_get()
Referenced by buffer_add_buffer.
uint32_t ssh_buffer_get_len(struct ssh_buffer_struct *buffer)
Get the length of the buffer, not counting position.
buffer The buffer to get the length from. The length of the buffer. buffer_get()
Referenced by ssh_buffer_unpack_va, ssh_gssapi_get_creds.
uint32_t buffer_get_rest_len(struct ssh_buffer_struct *buffer)
Get the length of the buffer from the current position.
buffer The buffer to get the length from. The length of the buffer. buffer_get_rest()
Referenced by buffer_add_buffer, sftp_write, ssh_channel_is_eof, ssh_channel_poll, ssh_channel_read_timeout, ssh_pcap_file_write_packet, ssh_socket_buffered_write_bytes.
uint32_t buffer_pass_bytes(struct ssh_buffer_struct *buffer, uint32_t len)
Advance the position in the buffer.
This has effect to "eat" bytes at head of the buffer. buffer The buffer to advance the position. len The number of bytes to eat. The new size of the buffer.
uint32_t buffer_pass_bytes_end(struct ssh_buffer_struct *buffer, uint32_t len)
Cut the end of the buffer.
buffer The buffer to cut. len The number of bytes to remove from the tail. The new size of the buffer.
uint32_t buffer_get_data(struct ssh_buffer_struct *buffer, void *data, uint32_t len)
Get the remaining data out of the buffer and adjust the read pointer.
buffer The buffer to read. data The data buffer where to store the data. len The length to read from the buffer. 0 if there is not enough data in buffer, len otherwise.
References ssh_buffer_validate_length.
Referenced by buffer_get_mpint, buffer_get_ssh_string, buffer_get_u32, buffer_get_u64, buffer_get_u8, ssh_buffer_unpack_va.
int buffer_get_u8(struct ssh_buffer_struct *buffer, uint8_t *data)
Get a 8 bits unsigned int out of the buffer and adjusts the read pointer.
buffer The buffer to read. data A pointer to a uint8_t where to store the data. 0 if there is not enough data in buffer, 1 otherwise.
References buffer_get_data.
Referenced by ssh_buffer_unpack_va.
int buffer_get_u32(struct ssh_buffer_struct *buffer, uint32_t *data)
gets a 32 bits unsigned int out of the buffer. Adjusts the read pointer.
buffer Buffer to read data pointer to a uint32_t where to store the data 0 if there is not enough data in buffer 4 otherwise.
References buffer_get_data.
Referenced by buffer_get_ssh_string, ssh_buffer_unpack_va.
int buffer_get_u64(struct ssh_buffer_struct *buffer, uint64_t *data)
Get a 64 bits unsigned int out of the buffer and adjusts the read pointer.
buffer The buffer to read. data A pointer to a uint64_t where to store the data. 0 if there is not enough data in buffer, 8 otherwise.
References buffer_get_data.
Referenced by ssh_buffer_unpack_va.
int ssh_buffer_validate_length(struct ssh_buffer_struct *buffer, size_t len)
Valdiates that the given length can be obtained from the buffer.
buffer The buffer to read from. len The length to be checked. SSH_OK if the length is valid, SSH_ERROR otherwise.
Referenced by buffer_get_data, buffer_get_ssh_string, ssh_buffer_unpack_va.
struct ssh_string_struct* buffer_get_ssh_string(struct ssh_buffer_struct *buffer)
Get a SSH String out of the buffer and adjusts the read pointer.
buffer The buffer to read. The SSH String, NULL on error.
References buffer_get_data, buffer_get_u32, ssh_buffer_validate_length, ssh_string_data, ssh_string_new.
Referenced by ssh_buffer_unpack_va, ssh_gssapi_get_creds, ssh_message_free, SSH_PACKET_CALLBACK, ssh_pki_import_pubkey_base64, ssh_pki_import_pubkey_blob.
struct ssh_string_struct* buffer_get_mpint(struct ssh_buffer_struct *buffer)
Get a mpint out of the buffer and adjusts the read pointer.
This function is SSH-1 only. buffer The buffer to read. The SSH String containing the mpint, NULL on error.
References buffer_get_data, ssh_string_data, ssh_string_new.
int ssh_buffer_pack_va(struct ssh_buffer_struct *buffer, const char *format, int argc, va_list ap)
Add multiple values in a buffer on a single function call.
buffer The buffer to add to format A format string of arguments. ap A va_list of arguments. SSH_OK on success SSH_ERROR on error ssh_buffer_add_format() for format list values.
References buffer_add_ssh_string, buffer_add_u16, buffer_add_u32, buffer_add_u64, buffer_add_u8, ssh_buffer_add_data.
Referenced by _ssh_buffer_pack.
int _ssh_buffer_pack(struct ssh_buffer_struct *buffer, const char *format, int argc,...)
Add multiple values in a buffer on a single function call.
buffer The buffer to add to format A format string of arguments. This string contains single letters describing the order and type of arguments: 'b': uint8_t (pushed in network byte order) 'w': uint16_t (pushed in network byte order) 'd': uint32_t (pushed in network byte order) 'q': uint64_t (pushed in network byte order) 'S': ssh_string 's': char * (C string, pushed as SSH string) 't': char * (C string, pushed as free text) 'P': size_t, void * (len of data, pointer to data) only pushes data. 'B': bignum (pushed as SSH string) SSH_OK on success SSH_ERROR on error when using 'P' with a constant size (e.g. 8), do not forget to cast to (size_t).
References ssh_buffer_pack_va.
int ssh_buffer_unpack_va(struct ssh_buffer_struct *buffer, const char *format, int argc, va_list ap)
Get multiple values from a buffer on a single function call.
buffer The buffer to get from format A format string of arguments. ap A va_list of arguments. SSH_OK on success SSH_ERROR on error ssh_buffer_get_format() for format list values.
References buffer_get_data, buffer_get_ssh_string, buffer_get_u32, buffer_get_u64, buffer_get_u8, ssh_buffer_get_len, ssh_buffer_validate_length.
Referenced by _ssh_buffer_unpack.
int _ssh_buffer_unpack(struct ssh_buffer_struct *buffer, const char *format, int argc,...)
Get multiple values from a buffer on a single function call.
buffer The buffer to get from format A format string of arguments. This string contains single letters describing the order and type of arguments: 'b': uint8_t * (pulled in network byte order) 'w': uint16_t * (pulled in network byte order) 'd': uint32_t * (pulled in network byte order) 'q': uint64_t * (pulled in network byte order) 'S': ssh_string * 's': char ** (C string, pulled as SSH string) 'P': size_t, void ** (len of data, pointer to data) only pulls data. SSH_OK on success SSH_ERROR on error when using 'P' with a constant size (e.g. 8), do not forget to cast to (size_t).
References ssh_buffer_unpack_va.