libssh_socket
ssh_socket_states_e
int sockets_initialized
static int ssh_socket_unbuffered_read(ssh_socket s, void *buffer, uint32_t len)
read len bytes from socket into buffer
static int ssh_socket_unbuffered_write(ssh_socket s, const void *buffer, uint32_t len)
writes len bytes from buffer to socket
int ssh_socket_init(void)
inits the socket system (windows specific)
Referenced by ssh_init.
void ssh_socket_cleanup(void)
Cleanup the socket system.
Referenced by ssh_finalize.
ssh_socket ssh_socket_new(ssh_session session)
creates a new Socket object
References ssh_buffer_free, ssh_buffer_new.
Referenced by ssh_bind_accept_fd, ssh_new.
void ssh_socket_reset(ssh_socket s)
Reset the state of a socket so it looks brand-new.
s socket to rest
References ssh_buffer_reinit.
Referenced by ssh_disconnect.
void ssh_socket_set_callbacks(ssh_socket s, ssh_socket_callbacks callbacks)
the socket callbacks, i.e. callbacks to be called upon a socket event.
s socket to set callbacks on. callbacks a ssh_socket_callback object reference.
int ssh_socket_pollcallback(struct ssh_poll_handle_struct *p, socket_t fd, int revents, void *v_s)
SSH poll callback.
This callback will be used when an event caught on the socket. p Poll object this callback belongs to. fd The raw socket. revents The current poll events on the socket. userdata Userdata to be passed to the callback function, in this case the socket object. 0 on success, < 0 when the poll object has been removed from its poll context.
References ssh_socket_is_open.
Referenced by ssh_socket_get_poll_handle_in, ssh_socket_get_poll_handle_out.
ssh_poll_handle ssh_socket_get_poll_handle_in(ssh_socket s)
returns the input poll handle corresponding to the socket, creates it if it does not exist.
allocated and initialized ssh_poll_handle object
References ssh_poll_new, ssh_socket_pollcallback.
Referenced by ssh_handle_packets, ssh_poll_ctx_add_socket.
ssh_poll_handle ssh_socket_get_poll_handle_out(ssh_socket s)
returns the output poll handle corresponding to the socket, creates it if it does not exist.
allocated and initialized ssh_poll_handle object
References ssh_poll_new, ssh_socket_pollcallback.
Referenced by ssh_bind_accept_fd, ssh_handle_packets, ssh_poll_ctx_add_socket.
void ssh_socket_free(ssh_socket s)
Deletes a socket object.
References ssh_buffer_free, ssh_socket_close.
Referenced by ssh_bind_accept, ssh_bind_accept_fd.
int ssh_socket_unix(ssh_socket s, const char *path)
void ssh_socket_close(ssh_socket s)
closes a socket
References ssh_poll_free, ssh_socket_is_open.
Referenced by ssh_disconnect, ssh_silent_disconnect, ssh_socket_free.
void ssh_socket_set_fd(ssh_socket s, socket_t fd)
sets the file descriptor of the socket.
s ssh_socket to update fd file descriptor to set this function updates boths the input and output file descriptors
References ssh_poll_set_fd.
Referenced by ssh_bind_accept_fd.
void ssh_socket_set_fd_in(ssh_socket s, socket_t fd)
sets the input file descriptor of the socket.
s ssh_socket to update fd file descriptor to set
References ssh_poll_set_fd.
void ssh_socket_set_fd_out(ssh_socket s, socket_t fd)
sets the output file descriptor of the socket.
s ssh_socket to update fd file descriptor to set
References ssh_poll_set_fd.
socket_t ssh_socket_get_fd_in(ssh_socket s)
returns the input file descriptor of the socket
Referenced by ssh_get_fd.
int ssh_socket_is_open(ssh_socket s)
returns nonzero if the socket is open
Referenced by ssh_disconnect, ssh_send_debug, ssh_send_ignore, ssh_socket_close, ssh_socket_nonblocking_flush, ssh_socket_pollcallback.
int ssh_socket_fd_isset(ssh_socket s, fd_set *set)
returns nonzero if the current socket is in the fd_set
void ssh_socket_fd_set(ssh_socket s, fd_set *set, socket_t *max_fd)
sets the current fd in a fd_set and updates the max_fd
int ssh_socket_write(ssh_socket s, const void *buffer, int len)
buffered write of data
SSH_OK, or SSH_ERROR has no effect on socket before a flush
References ssh_buffer_add_data, ssh_socket_nonblocking_flush.
int ssh_socket_nonblocking_flush(ssh_socket s)
starts a nonblocking flush of the output buffer
References ssh_socket_is_open.
Referenced by ssh_socket_write.
void ssh_socket_set_write_wontblock(ssh_socket s)
void ssh_socket_set_read_wontblock(ssh_socket s)
void ssh_socket_set_except(ssh_socket s)
int ssh_socket_data_available(ssh_socket s)
int ssh_socket_data_writable(ssh_socket s)
int ssh_socket_buffered_write_bytes(ssh_socket s)
returns the number of outgoing bytes currently buffered
s the socket numbers of bytes buffered, or 0 if the socket isn't connected
References buffer_get_rest_len.
int ssh_socket_get_status(ssh_socket s)
int ssh_socket_get_poll_flags(ssh_socket s)
int ssh_socket_set_nonblocking(socket_t fd)
int ssh_socket_set_blocking(socket_t fd)
int ssh_socket_connect(ssh_socket s, const char *host, int port, const char *bind_addr)
Launches a socket connection If a the socket connected callback has been defined and a poll object exists, this call will be non blocking.
s socket to connect. host hostname or ip address to connect to. port port number to connect to. bind_addr address to bind to, or NULL for default. SSH_OK socket is being connected. SSH_ERROR error while connecting to remote host. BugIt only tries connecting to one of the available AI's which is problematic for hosts having DNS fail-over.
void ssh_execute_command(const char *command, socket_t in, socket_t out)
executes a command and redirect input and outputs
command command to execute in input file descriptor out output file descriptor
int ssh_socket_connect_proxycommand(ssh_socket s, const char *command)
Open a socket on a ProxyCommand This call will always be nonblocking.
s socket to connect. command Command to execute. SSH_OK socket is being connected. SSH_ERROR error while executing the command.