session.h
SSH_SESSION_FLAG_BLOCKING
SSH_SESSION_FLAG_AUTHENTICATED
SSH_TIMEOUT_INFINITE
SSH_TIMEOUT_USER
SSH_TIMEOUT_DEFAULT
SSH_TIMEOUT_NONBLOCKING
ssh_session_state_e
ssh_dh_state_e
ssh_pending_call_e
typedef int(* ssh_termination_function) (void *user))(void *user)
a termination function evaluates the status of an object
user[in] object to evaluate 1 if the polling routine should terminate, 0 instead
int ssh_handle_packets(ssh_session session, int timeout)
Poll the current session for an event and call the appropriate callbacks. This function will not loop until the timeout is expired.
This will block until one event happens. session The session handle to use. timeout Set an upper limit on the time for which this function will block, in milliseconds. Specifying SSH_TIMEOUT_INFINITE (-1) means an infinite timeout. Specifying SSH_TIMEOUT_USER means to use the timeout specified in options. 0 means poll will return immediately. This parameter is passed to the poll() function. SSH_OK on success, SSH_ERROR otherwise.
References ssh_socket_get_poll_handle_in, ssh_socket_get_poll_handle_out, ssh_poll_add_events, ssh_poll_get_ctx, ssh_poll_get_default_ctx, ssh_poll_ctx_add, ssh_is_blocking, ssh_make_milliseconds, ssh_poll_ctx_dopoll.
Referenced by channel_read_buffer, ssh_channel_poll, ssh_handle_packets_termination, ssh_send_ignore, ssh_send_debug.
int ssh_handle_packets_termination(ssh_session session, int timeout, ssh_termination_function fct, void *user)
Poll the current session for an event and call the appropriate callbacks.
This will block until termination function returns true, or timeout expired. session The session handle to use. timeout Set an upper limit on the time for which this function will block, in milliseconds. Specifying SSH_TIMEOUT_INFINITE (-1) means an infinite timeout. Specifying SSH_TIMEOUT_USER means to use the timeout specified in options. 0 means poll will return immediately. SSH_TIMEOUT_DEFAULT uses blocking parameters of the session. This parameter is passed to the poll() function. fct Termination function to be used to determine if it is possible to stop polling. user User parameter to be passed to fct termination function. SSH_OK on success, SSH_ERROR otherwise.
References ssh_is_blocking, ssh_make_milliseconds, ssh_timestamp_init, ssh_handle_packets, ssh_timeout_elapsed, ssh_timeout_update.
Referenced by ssh_channel_poll_timeout, ssh_channel_get_exit_status, ssh_blocking_flush.
void ssh_socket_exception_callback(int code, int errno_code, void *user)
Callback to be called when the socket received an exception code.
user is a pointer to session